### ISSUE TITLE
Erreur streaming sur Android

### ISSUE THREAD

**Issue by eftov** [eftov/Kimote#2]
logs quand on veut streamer un film ou un épisode : 
```
04-10 15:50:36.894    3860-3860/com.ionicframework.kimote371863 D/CordovaLog﹕ file:///android_asset/www/js/controllers/MoviesCtrl.js: Line 55 : streamUrl : http://kodi:pass@172.16.90.251:8080/vfs/%2FUsers%2FBenjamin%2FDownloads%2FKodi%2FMovies%2FInterstellar.mp4
04-10 15:50:36.894    3860-3860/com.ionicframework.kimote371863 I/chromium﹕ [INFO:CONSOLE(55)] "streamUrl : http://kodi:pass@172.16.90.251:8080/vfs/%2FUsers%2FBenjamin%2FDownloads%2FKodi%2FMovies%2FInterstellar.mp4", source: file:///android_asset/www/js/controllers/MoviesCtrl.js (55)
04-10 15:50:37.329    3860-3928/com.ionicframework.kimote371863 D/MediaResourceGetter﹕ ethernet/wifi connection detected

04-10 15:51:08.028    3860-3928/com.ionicframework.kimote371863 E/MediaResourceGetter﹕ Error configuring data source
    java.lang.RuntimeException: setDataSource failed: status = 0x80000000
            at android.media.MediaMetadataRetriever._setDataSource(Native Method)
            at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:105)
            at com.android.org.chromium.content.browser.MediaResourceGetter.configure(MediaResourceGetter.java:407)
            at com.android.org.chromium.content.browser.MediaResourceGetter.configure(MediaResourceGetter.java:251)
            at com.android.org.chromium.content.browser.MediaResourceGetter.extract(MediaResourceGetter.java:145)
            at com.android.org.chromium.content.browser.MediaResourceGetter.extractMediaMetadata(MediaResourceGetter.java:117)
04-10 15:51:08.031    3860-3928/com.ionicframework.kimote371863 E/MediaResourceGetter﹕ Unable to configure metadata extractor

04-10 15:51:25.225    3860-3860/com.ionicframework.kimote371863 D/MediaPlayer﹕ Couldn't open file on client side, trying server side

04-10 15:51:55.769    3860-3880/com.ionicframework.kimote371863 E/MediaPlayer﹕ error (1, -2147483648)
04-10 15:51:55.769    3860-3860/com.ionicframework.kimote371863 E/MediaPlayer﹕ Error (1,-2147483648)
```

**Comment by eftov** [comment]
Issue resolved with cordova-android update 4.0.0
